### PR TITLE
Pyro update

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by willnewton** [comment]
@floion I pushed a couple of minor required changes to this branch. Along with the rest of the Pyro support PRs (up to and including https://github.com/resin-os/meta-resin/pull/826) this allows the build to proceed until building u-boot where it fails. I'm not sure why this is but I think there's quite a good chance that it's odroid specific.

**Comment by agherzan** [comment]
@willnewton this needs a rebase.

**Comment by willnewton** [comment]
@agherzan @floion rebased. The current issue is that the aufs patches no longer apply to the latest 3.10 stable kernel. Unfortunately it looks like the C1 is still stuck on 3.10 on Pyro (master of meta-odroid moves to 4.12).

**Comment by willnewton** [comment]
@floion @agherzan this now builds but I don't have hardware to test. The two boards use quite different kernels and u-boot and there was quite a bit of work to get the C1 working with Pyro as it uses very old and custom versions of both.

**Comment by willnewton** [comment]
This currently fails in the XU4 build due to missing files which look like the first level bootloader e.g. bl1.bin.hardkernel. It's possible these files are not needed any more but seems unlikely. It would require someone with hardware and a bit of investigation to look into what the correct fix is here.

**Comment by floion** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
Superseded by https://github.com/resin-os/resin-odroid/pull/52

**Pull request closed without merging**
